ALTER TABLE SAC_Evaluaciones
DROP CONSTRAINT PK__SAC_Evaluaciones__4AE49A27

ALTER TABLE SAC_Evaluaciones ALTER COLUMN id int

ALTER TABLE SAC_Evaluaciones
ADD CONSTRAINT PK__SAC_Evaluaciones__4AE49A27 PRIMARY KEY (id)